/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as CalculatorRouteImport } from "./routes/calculator";
import { Route as CountriesRouteImport } from "./routes/countries";
import { Route as EconomyRouteImport } from "./routes/economy";
import { Route as JobsRouteImport } from "./routes/jobs";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const CalculatorRoute = CalculatorRouteImport.update({
  id: "/calculator",
  path: "/calculator",
  getParentRoute: () => rootRouteImport,
} as any);
const CountriesRoute = CountriesRouteImport.update({
  id: "/countries",
  path: "/countries",
  getParentRoute: () => rootRouteImport,
} as any);
const EconomyRoute = EconomyRouteImport.update({
  id: "/economy",
  path: "/economy",
  getParentRoute: () => rootRouteImport,
} as any);
const JobsRoute = JobsRouteImport.update({
  id: "/jobs",
  path: "/jobs",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/calculator": typeof CalculatorRoute;
  "/countries": typeof CountriesRoute;
  "/economy": typeof EconomyRoute;
  "/jobs": typeof JobsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/calculator": typeof CalculatorRoute;
  "/countries": typeof CountriesRoute;
  "/economy": typeof EconomyRoute;
  "/jobs": typeof JobsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/calculator": typeof CalculatorRoute;
  "/countries": typeof CountriesRoute;
  "/economy": typeof EconomyRoute;
  "/jobs": typeof JobsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$" | "/calculator" | "/countries" | "/economy" | "/jobs";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$" | "/calculator" | "/countries" | "/economy" | "/jobs";
  id: "__root__" | "/" | "/$" | "/calculator" | "/countries" | "/economy" | "/jobs";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  CalculatorRoute: typeof CalculatorRoute;
  CountriesRoute: typeof CountriesRoute;
  EconomyRoute: typeof EconomyRoute;
  JobsRoute: typeof JobsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calculator": {
      id: "/calculator";
      path: "/calculator";
      fullPath: "/calculator";
      preLoaderRoute: typeof CalculatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/countries": {
      id: "/countries";
      path: "/countries";
      fullPath: "/countries";
      preLoaderRoute: typeof CountriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/economy": {
      id: "/economy";
      path: "/economy";
      fullPath: "/economy";
      preLoaderRoute: typeof EconomyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/jobs": {
      id: "/jobs";
      path: "/jobs";
      fullPath: "/jobs";
      preLoaderRoute: typeof JobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CalculatorRoute: CalculatorRoute,
  CountriesRoute: CountriesRoute,
  EconomyRoute: EconomyRoute,
  JobsRoute: JobsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
