/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MarketItemCodeRouteImport } from './routes/market_.$itemCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketItemCodeRoute = MarketItemCodeRouteImport.update({
  id: '/market_/$itemCode',
  path: '/market/$itemCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calculator': typeof CalculatorRoute
  '/companies': typeof CompaniesRoute
  '/countries': typeof CountriesRoute
  '/growth': typeof GrowthRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market/$itemCode': typeof MarketItemCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calculator': typeof CalculatorRoute
  '/companies': typeof CompaniesRoute
  '/countries': typeof CountriesRoute
  '/growth': typeof GrowthRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market/$itemCode': typeof MarketItemCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/calculator': typeof CalculatorRoute
  '/companies': typeof CompaniesRoute
  '/countries': typeof CountriesRoute
  '/growth': typeof GrowthRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/market_/$itemCode': typeof MarketItemCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/calculator'
    | '/companies'
    | '/countries'
    | '/growth'
    | '/jobs'
    | '/market'
    | '/market/$itemCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/calculator'
    | '/companies'
    | '/countries'
    | '/growth'
    | '/jobs'
    | '/market'
    | '/market/$itemCode'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/calculator'
    | '/companies'
    | '/countries'
    | '/growth'
    | '/jobs'
    | '/market'
    | '/market_/$itemCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CalculatorRoute: typeof CalculatorRoute
  CompaniesRoute: typeof CompaniesRoute
  CountriesRoute: typeof CountriesRoute
  GrowthRoute: typeof GrowthRoute
  JobsRoute: typeof JobsRoute
  MarketRoute: typeof MarketRoute
  MarketItemCodeRoute: typeof MarketItemCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market_/$itemCode': {
      id: '/market_/$itemCode'
      path: '/market/$itemCode'
      fullPath: '/market/$itemCode'
      preLoaderRoute: typeof MarketItemCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CalculatorRoute: CalculatorRoute,
  CompaniesRoute: CompaniesRoute,
  CountriesRoute: CountriesRoute,
  GrowthRoute: GrowthRoute,
  JobsRoute: JobsRoute,
  MarketRoute: MarketRoute,
  MarketItemCodeRoute: MarketItemCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
